name: Release

on:
  push:
    branches:
      - main
      - pre/*

########################################################################
# 1. Build
########################################################################
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: |
          sudo apt update
          sudo apt install -y git

      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: false }

      - name: Build and validate package
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install --upgrade setuptools wheel hatchling
          uv sync --frozen
          uv pip install -e .
          uv build                      # creates dist/*
          uv pip install --upgrade pkginfo==1.12.0 twine==6.0.1
          python -m twine check dist/*

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

#######################################################################
# 2. Test
#######################################################################
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv sync --frozen
          uv pip install -e .

      - name: Run linting / formatting
        run: |
          . .venv/bin/activate
          ruff check python_lib_template tests
          black --check python_lib_template tests
          isort --check-only python_lib_template tests

###############################################################################
# 3. semantic-version
###############################################################################
  semantic-version:
    name: Version & GitHub release
    runs-on: ubuntu-latest
    needs: [build, test]
    if: |
      github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/pre/')
    permissions:                     # ← no id-token here
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            @semantic-release/git
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

###############################################################################
# 4. publish
###############################################################################
  publish:
    name: Publish to PyPI (trusted)
    runs-on: ubuntu-latest
    needs: semantic-version
    permissions:
      id-token: write          # minimal scope for OIDC
    steps:
      - uses: actions/checkout@v4     # provenance only

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distributions
        uses: pypa/gh-action-pypi-publish@v1
        with:
          packages-dir: dist/
          verbose: true
